### ISSUE TITLE
New authentication in Vertec xml server

### ISSUE THREAD

**Issue by brtx** [dimitri-koenig/simple-vertec-api#100]
Hi Dimitri,

my company set up a vertec xml server only supporting the new authentication and not the legacy one anymore: https://www.vertec.com/de/support/kb/technik-und-datenmodell/vertecservice/xml/xmlschnittstelle/

simple-vertec-api still uses the legacy authentication. Do you have any plans on implementing the new one?

Thanks a lot for this library, I used it for synchronising vertec and toggl and it helped me a lot:
https://www.npmjs.com/package/toggl-vertec

Best regards, Stefan

**Comment by dimitri-koenig** [comment]
Hi Stefan

As soon as the company, where I've developed a huge internal reportings application, is ready for the 6.2 upgrade I will also update the auth method. Unfortunately I don't have any dates yet. But I'll keep you in the loop via this issue.

Any plans on publishing your toggl-vertec on Github?

**Comment by brtx** [comment]
Hi Dimitri,

awesome, thanks.

So far toggl-vertec was self-hosting the xml server, which is pretty nasty, looking forward to get rid of this dependency. I just made it configurable so it does not need to host the server anymore. Last piece missing now is the new authentication. I am in holidays, so I don't have access to our server at the moment and cannot test my changes, once I am back I may look into it also if I find some time.

Moving the project to Github was in the list for a while. I just wanted to include some licensing info, which I finally did today, so here we go: https://github.com/brtx/toggl-vertec

**Comment by dimitri-koenig** [comment]
Nice code. Well done.

**Comment by brtx** [comment]
Any news on this issue? My company now upgraded to 6.2 and the self-hosted hack doesn't work anymore. I may have some time these days also to checkout your code.

**Comment by dimitri-koenig** [comment]
Things are moving... Looks like I could start working on the new auth process within the next couple of days. I'll post an update here...

**Comment by brtx** [comment]
I created a PR here: https://github.com/dimitri-koenig/simple-vertec-api/pull/101

**Comment by dimitri-koenig** [comment]
Thx for your code. I've put it all together in v4 branch and published a new beta npm package: simple-vertec-api@4.0.0-beta4

Could you check it out and test yourself? For me it works good now.

**Comment by brtx** [comment]
Cool, thanks a lot for integrating the PR. I am referencing your beta package now and so far it's working well for me.

**Comment by dimitri-koenig** [comment]
Thx for your feedback. I will release a final v4 release as soon as my customer goes live with the new 6.2 version

**Comment by dimitri-koenig** [comment]
So, finally, later then expected, but better later then never: v4 is out of beta, and it works, for both Vertec 6.2 and Vertec 6.3
