### ISSUE TITLE
Is there a "disconnect" method?

### ISSUE THREAD

**Issue by oliver-la** [dimitri-koenig/simple-vertec-api#99]
First of all, thanks for writing this library.

The SimpleVertecApi()-call gets stuck and won't let the application exit until I hit CTRL+C.  Is there something I'm missing?

This is the code I have:

```
var vertec = require('simple-vertec-api').SimpleVertecApi;
var query = require('simple-vertec-api').SimpleVertecQuery;

var api = new vertec('http://192.168.xx.xx:8090/xml', 'XXXXXXX', 'YYYYYYYY', true);

```

Sure, I could use `process.exit(0);` but that does not seem ideal to me.

Also, it doesn't matter at all if I use wrong credentials, it won't throw an exception or at least show that something is wrong.

**Comment by dimitri-koenig** [comment]
Actually this is just the bootstrap code to get you all set up for your api calls.

For example:
```
new query()
    .whereOcl('Leistung')
    .whereSql("(datum >= {ts '2018-01-01 00:00:00'})")
    .orderBy('datum')
    .addFields([
        'bearbeiter',
        'text',
        'minutenInt',
        'datum'
    ])
    .get(refresh);
```

**Comment by oliver-la** [comment]
Sorry, I should've attached my complete code. I'm querying the API afterwards of course. Using your example it still gets stuck:

```
var vertec = require('simple-vertec-api').SimpleVertecApi;
var query = require('simple-vertec-api').SimpleVertecQuery;

var api = new vertec(process.env.VERTEC_XML_API_URL, process.env.VERTEC_USERNAME, process.env.VERTEC_PASSWORD, true);

query.setApi(api);

new query()
    .whereOcl('Leistung')
    .whereSql("(datum >= '2018-02-01 00:00:00')")
    .orderBy('datum')
    .addFields([
        'bearbeiter',
        'text',
        'minutenInt',
        'datum'
    ])
    .then(function(response) {
        // do something with the result
        console.log(response);
    });
```

I think the issue is with the "new vertec(...)"-call. The promise of the query call resolves just fine and gets me the desired response.

Node version is v8.9.4

**Comment by dimitri-koenig** [comment]
You forgot the "get()" method call. This one works for me:

```
var vertec = require('simple-vertec-api').SimpleVertecApi;
var query = require('simple-vertec-api').SimpleVertecQuery;

var api = new vertec(process.env.VERTEC_XML_API_URL, process.env.VERTEC_USERNAME, process.env.VERTEC_PASSWORD, true);

query.setApi(api);

new query()
    .whereOcl('Leistung')
    .whereSql("(datum >= '2018-02-01 00:00:00')")
    .orderBy('datum')
    .addFields([
        'bearbeiter',
        'text',
        'minutenInt',
        'datum'
    ])
    .get()
    .then(function(response) {
        // do something with the result
        console.log(response);
    });
```

**Comment by oliver-la** [comment]
Even then it gets stuck, unless I remove this line in your source code: (stuck = the application is still running, but not producing any output past the query)

https://github.com/dimitri-koenig/simple-vertec-api/blob/develop/lib/simple-vertec-api.js#L42

You never clear the interval, so it goes on forever and thus won't let the application exit. 

Seems like it works for you just fine. Perhaps you didn't push your most recent changes to GitHub/NPM?

**Comment by dimitri-koenig** [comment]
Now I get your point. Well, there was never a need for such a disconnect function. Vertec calls are always stateless, it's always just one call and that's it, no connect function whatsoever.

If you really need one feel free to contribute.
